### ISSUE TITLE
DAG successful even if a Tool fails

### ISSUE THREAD

**Issue by ghost** [Spine-project/Spine-Toolbox#1443]
## Steps to reproduce

1. Create a Python tool which will fail using e.g. this script *fail.py*:
    ```python
    raise Exception
    ````
2. Execute the project. Python console should show:
    ```python
    >>> # Running 'python fail.py'
    File "<stdin>", line 1, in <module>
    Traceback (most recent call last):
    Exception
    raise Exception
    File "fail.py", line 1, in <module>
    ```

However, both the event log and the execution log indicate that everything went fine:

```
-------------------------------------------------
Executing All Directed Acyclic Graphs
-------------------------------------------------
Starting DAG 1/1
Order: fail
DAG 1/1 completed successfully
```

```
[01-07-2021 16:32:23] ***Executing Tool fail***
[01-07-2021 16:32:23] *** Executing Tool specification fail in source directory ***
[01-07-2021 16:32:23] *** Starting execution on persistent process C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\python.exe ***
[01-07-2021 16:32:23] See Console for messages
[01-07-2021 16:32:23] *** Archiving output files to results directory ***
[01-07-2021 16:32:23] 	No output files defined for this Tool specification. Tip
[01-07-2021 16:32:23] Executing Tool fail finished
```

Tool item also shows a green check icon.

## Expected behaviour

The item execution should fail and crash the whole DAG. This would be indicated in all logs.

**Comment by manuelma** [comment]
It also affects the Jupyter console. One idea would be to say that the tool failed if the last message received was a stdout message (or in Jupyter, an "error" message). But for example Julia warnings also go to the stdout (don't know about Python), so we would be making an assumption here if we go with my idea. For example, if a Julia tool just issues a warning and succeeds, we would still consider that if failed.

But I think that's good enough. Any other ideas?

**Comment by jkiviluo** [comment]
I think we can catch only those consoles/execution errors where we know the failure behavior for sure. Hopefully that is true for all Python and Julia code as well as Jupyter conosle. However, we can't assume that for executables and we just need to let the project continue running. The output from the tools will be visible in their logs and hopefully that is sufficient.

We could also try to establish a method for catching errors where the tool specification is used to indicate how the tool can fail, but that is for the roadmap.

**Comment by manuelma** [comment]
For executables that don't run in console, we can look at the return code of the python subprocess that runs the executable, and that will tell us the outcome with 100 % certaintt. That's good. The problem is for console execution where we don't have an error code, just stdin and stdout and we need to interpret that as best as we can.

**Comment by PekkaSavolainen** [comment]
I think this used to work previously. We read the execution reply message coming from the Jupyter client/manager after a script has been executed. Now, it looks like the Jupyter client/manager reports that everything went ok even if the code fails with a syntax error. We have this in KernelExecutionManager and this does not return -1 when it should because st is always 'ok' for some reason.

```
    def _do_run(self):
        try:
            self._kernel_client.wait_for_ready(timeout=self._startup_timeout)
        except RuntimeError as e:
            msg = dict(type="execution_failed_to_start", error=str(e), **self._msg_head)
            self._logger.msg_kernel_execution.emit(msg)
            return
        msg = dict(type="execution_started", **self._msg_head)
        self._logger.msg_kernel_execution.emit(msg)
        for cmd in self._commands:
            reply = self._kernel_client.execute_interactive(cmd, output_hook=lambda msg: None)
            st = reply["content"]["status"]
            if st != "ok":  # st IS ALWAYS 'ok'!!!!
                return -1
        return 0
```

st should be 'error' or 'aborted' when there's a problem.

**Comment by PekkaSavolainen** [comment]
Interesting. This problem does not concern Julia Tool specs (Try it by putting some syntax error into a Julia script) in Jupyter Console.

**Comment by manuelma** [comment]
@PekkaSavolainen  What do you think about the homemade console solution I propose: if the last received message was stdout, we consider the execution has failed, otherwise it succeeded.

**Comment by manuelma** [comment]
I think you're missing that the homemade console just runs `python - i` to start, and then `eval script` (or something along those lines) to execute; *not* `pyhton script.py`. There is no return code, just stdin and stdout.

**Comment by PekkaSavolainen** [comment]
> Could it be wrapped inside an error handling block?

Not sure but it would be an interesting thing to try.

> I could not find the piece of code that starts the script in the console, could you help?

Looks like we write the command to be executed to the persistent console's *stdin* in

https://github.com/Spine-project/spine-engine/blob/135435d7d434629a69fc01c40984969eb085d10f/spine_engine/execution_managers/persistent_execution_manager.py#L172

The persistent console is a subprocess.Popen object that has been opened with a command that looks something like `python -q -i -c ...`.

**Comment by ererkka** [comment]
All right, thanks! If we could somehow check this in `PersistentManagerBase._issue_command()`:

```python
if isinstance(sys.last_type, BaseException):
    return false
```

See https://docs.python.org/3.8/library/sys.html#sys.last_type

**Comment by PekkaSavolainen** [comment]
I went with @manuelma's suggestion to make a Python Tool (and the whole DAG) fail when executing a Python Tool spec script fails. A Tool fails if there's something printed to `stderr` while executing a script. At least in case of typos or something it looks like it's working very well.

**Comment by ererkka** [comment]
Nice, very good solution! I tested and it works as expected.

**Comment by PekkaSavolainen** [comment]
Not so fast :). Python Jupyter Console still has the same problem. Don't really know what to do about it, other than try a previous jupyter_client, ipython, or qtconsole version since I'm 99% sure that it used to work in the past.

**Comment by PekkaSavolainen** [comment]
I found the problem in Python Jupyter Console. Basically we are throwing the error message in the trash because we are not listening to the correct channel for the error message. Fix coming up.

**Comment by PekkaSavolainen** [comment]
Done.

**Comment by manuelma** [comment]
There's still an issue here. As I was saying above, Julia warnings go to stderr (maybe the same is true for other  languages?) In SpineOpt, we issue a warning about the dataset missing some elements, which happens whenever one uses an oldie db. This means that a tool running SpineOpt may report that it failed, even if it just went through successfully with a warning.

This commit https://github.com/Spine-project/spine-engine/commit/1657a3dc992c567b9104cebe805f270623fb187b

...doesn't account for that fact. My suggestion above was to only report "failed" if the *last* message went to stderr. Do you think we can use that instead?

**Comment by ererkka** [comment]
I think that is a good suggestion to only check the last message.

**Comment by PekkaSavolainen** [comment]
> My suggestion above was to only report "failed" if the last message went to stderr.

Yes, should be better.

**Comment by soininen** [comment]
Should we have an option to disable this 'sniffing' in case a tool writes to stderr but doesn't actually fail?

**Comment by manuelma** [comment]
> Should we have an option to disable this 'sniffing' in case a tool writes to stderr but doesn't actually fail?

I think so, because the execution is actually stopped at the tool that failed. We can add a checkbox to the Tool properties UI that says "Ignore errors" (analogous to the ones we have in Importer and DS, do we have one for Exporter and DT too? Should we add them too?)

**Comment by soininen** [comment]
>  do we have one for Exporter and DT too?

Exporter already has this feature and DT doesn't need one.

**Comment by manuelma** [comment]
I just implemented my idea of checking the last message only for errors. I tested the basic console but didn't test the jupyter console though...

We still need to implement the "Ignore errors" checkbox as for Julia scripts, sometimes the only output is an [info] message about precompilation that also goes to stderr but shouldn't stop execution. Users can workaround this but adding a dummy print statement to the end of their scripts, but it's not awesome.

**Comment by PekkaSavolainen** [comment]
This issue was fixed for Jupyter Console in spine-engine commit 12d5b42. There's no need to do any stderr sniffing there.

**Comment by manuelma** [comment]
> This issue was fixed for Jupyter Console in spine-engine commit 12d5b42. There's no need to do any stderr sniffing there.

Why not? Which commit is that?

**Comment by PekkaSavolainen** [comment]
https://github.com/Spine-project/spine-engine/commit/12d5b4255755e70fb1f3914fdd0dac487c88b2da

**Comment by manuelma** [comment]
thank you! But I'm still missing something, how does that commit solve the issue? It seems to me that *any* error message will cause the tool to fail, and we only want it to fail if the *last* message is an error.

**Comment by PekkaSavolainen** [comment]
You can print as much as you want to stderr with Jupyter Console and it does not make the project item fail (as it should not) but if the return code of the `run(script)` command is non-zero (there's a traceback), the project item fails. It works as it's supposed to work. Tested on spine toolbox commit e932c84

**Comment by manuelma** [comment]
Thank you! Just one last thing, does the above applies for Julia tools too? You don't need to test it yourself Pekka, but I think it would be important to be sure.

**Comment by PekkaSavolainen** [comment]
The messaging protocol is the same whether Jupyter Console runs a Julia or a Python kernel so I'm pretty sure this applies to Julia Tools too.

**Comment by manuelma** [comment]
How do they know exactly that there was a traceback? We could try and use their solution in our homemade console... (instead of looking at the last message which is certainly not foolproof)

**Comment by manuelma** [comment]
I think what we need to do is wrap all commands issued to the persistent process manager in a `try except` block (or equivalent in the concerned programming language) that reraises the exception while setting a flag in the 'repl' module (spine_repl.py, SpineREPL.jl). Then we'd just need to check the flag right after the command finishes to see if it 'failed'.

This has to be more robust than checking the stderr, because e.g. I don't believe the python interactive session uses the stderr much (or at least not for tracebacks), and the Julia REPL uses it for warnings.

This would predate the fail_on_stderr flag but I think that's ok, we can get rid of it if my suggestion works. I will give it a try now.

**Comment by manuelma** [comment]
I just implemented my idea above and it seems to work. So now we completly ignore stderr for determining if a tool failed, and only rely on whether or not the code raised an unhandled exception. Seems like what most if not all users would except.

Now the question is what's the future of 'fail on stderr' - maybe we can repurpose it to something like "ignore errors", which if active would prevent the tool to fail if the code raised an exception. How does that sound?

**Comment by soininen** [comment]
> maybe we can repurpose it to something like "ignore errors"

I don't think we want to repurpose it. Originally, the option was a workaround for tools that wrote to stderr but didn't actually fail. If we don't rely on stderr for diagnostic purposes anymore, we should just drop the option.

**Comment by manuelma** [comment]
Thank you @soininen I removed the option. I think we are ready to close now, please reopen if needed.
