### ISSUE TITLE
Database editor fails to remove empty parameter value lists

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1467]
With empty database:

1. Create a new parameter value list but don't add any values
2. Right click the list, choose Remove
3. List does not disappear as it should

**Comment by soininen** [comment]
Fixed.

**Comment by manuelma** [comment]
Nice catch, thanks very much @soininen !

**Comment by manuelma** [comment]
Is it possible that this was the reason why we were still seeing orphan value items and we had to write `<removed>` for them?

**Comment by soininen** [comment]
> Is it possible that this was the reason why we were still seeing orphan value items and we had to write <removed> for them?

No, this is a corner case where we're removing stuff that is not yet in the database nor in any cache as you cannot store empty parameter value lists in Spine database.

We need `<removed>` for the short moment when the tree items have been already removed from the database but the tree view's model has not yet been updated and still contains the items.
