### ISSUE TITLE
Importers fails to import objects from pivoted data if parameter value cells contain None

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1644]
Consider the following input table where the parameter columns are empty:

| Object | parameter_1 | parameter_2 |
|--------|-------------|-------------|
| A      |             |             |
| B      |             |             |

and an Object class mapping:

![mappings_for_issue](https://user-images.githubusercontent.com/19147159/151493576-dd08d7b4-3882-434e-ae98-77b9740dfa6b.png)

One would expect Importer to import the objects even though they don't have the parameter values. However, the value cells would contain `None` if the input table came from an Excel file which in turn makes Importer to drop the objects altogether.

**Comment by soininen** [comment]
Fixed.

**Comment by IngridJSJ** [comment]
Hello, unfortunately the import still fails if there is an empty value in a csv
![image](https://user-images.githubusercontent.com/47012366/153643785-be77e588-d79f-42a1-91cd-7cb4f0eb13de.png)

I get this error:
('data', "Could not convert '' to type 'float' (near row 46)")

**Comment by soininen** [comment]
> Hello, unfortunately the import still fails if there is an empty value in a csv

That looks like a different problem than what this issue is about. Can you open a new issue with instructions and necessary test data to reproduce the problem you are facing?

**Comment by IngridJSJ** [comment]
Actually its all good now, I think I just changed the option of If values aleady exist: Merge indexes. 
Thank you!
